on:
  schedule:
    - cron: '0 */14 * * *' # Run every 5 hours
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v2
      with:
        token: ${{ secrets.USER_TOKEN }}
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name M8-Babbage
        git config user.email edwinjpr11@gmail.com
        git add .
        git commit -m "chore: update readme with github actions"
        git push
        fi
